# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_time', models.CharField(max_length=64, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('cmd_user', models.CharField(max_length=64, verbose_name='\u64cd\u4f5c\u4eba\u5458')),
                ('cmd_command', models.CharField(max_length=64, verbose_name='\u64cd\u4f5c\u6307\u4ee4')),
            ],
            options={
                'verbose_name': '\u64cd\u4f5c\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u64cd\u4f5c\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servergroup_id', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u5668\u7ec4ID')),
                ('servergroup_name', models.CharField(max_length=64, unique=True, verbose_name='\u670d\u52a1\u5668\u7ec4\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u7ec4\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u7ec4\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u5668ID')),
                ('server_name', models.CharField(max_length=64, verbose_name='\u670d\u52a1\u5668\u540d\u79f0')),
                ('server_ip', models.GenericIPAddressField(verbose_name='\u670d\u52a1\u5668IP')),
                ('service_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OM.ServerGroup', verbose_name='\u670d\u52a1\u5668\u5c5e\u7ec4')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u4fe1\u606f\u8868',
            },
        ),
        migrations.AddField(
            model_name='cmdhistory',
            name='cmd_server_group_id',
            field=models.ManyToManyField(to='OM.ServerGroup', verbose_name='\u64cd\u4f5c\u670d\u52a1\u5668\u7ec4ID'),
        ),
        migrations.AddField(
            model_name='cmdhistory',
            name='cmd_server_server_id',
            field=models.ManyToManyField(to='OM.ServerList', verbose_name='\u64cd\u4f5c\u670d\u52a1\u5668ID'),
        ),
    ]
