# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdhistory',
            name='cmd_server_group_id',
        ),
        migrations.AddField(
            model_name='cmdhistory',
            name='cmd_server_group_id',
            field=models.CharField(default='none', max_length=512, verbose_name='\u64cd\u4f5c\u670d\u52a1\u5668\u7ec4ID'),
        ),
        migrations.RemoveField(
            model_name='cmdhistory',
            name='cmd_server_server_id',
        ),
        migrations.AddField(
            model_name='cmdhistory',
            name='cmd_server_server_id',
            field=models.CharField(default='none', max_length=512, verbose_name='\u64cd\u4f5c\u670d\u52a1\u5668ID'),
        ),
    ]
