# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM', '0002_auto_20160909_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdhistory',
            name='client_ip',
            field=models.GenericIPAddressField(default='none', verbose_name='\u5ba2\u6237\u7aefIP'),
        ),
    ]
