# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM', '0006_auto_20160909_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='servergroup',
            name='server_members',
            field=models.CharField(default='null', max_length=512, verbose_name='\u4e0b\u5c5e\u670d\u52a1\u5668'),
        ),
    ]
