# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM', '0008_auto_20160910_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servergroup',
            name='server_members',
        ),
        migrations.AddField(
            model_name='servergroup',
            name='server_members',
            field=models.ManyToManyField(to='OM.ServerList', verbose_name='\u4e0b\u5c5e\u670d\u52a1\u5668'),
        ),
    ]
