# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM', '0010_auto_20160913_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='server_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u670d\u52a1\u5668ID'),
        ),
    ]
