# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM', '0011_auto_20160913_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='server_name',
            field=models.CharField(max_length=64, verbose_name='\u670d\u52a1\u5668\u4e3b\u673a\u540d'),
        ),
    ]
