# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM', '0012_auto_20160918_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdhistory',
            name='cmd_server_group_id',
            field=models.TextField(default='none', max_length=512, verbose_name='\u64cd\u4f5c\u670d\u52a1\u5668\u7ec4ID'),
        ),
        migrations.AlterField(
            model_name='cmdhistory',
            name='cmd_server_server_id',
            field=models.TextField(default='none', max_length=512, verbose_name='\u64cd\u4f5c\u670d\u52a1\u5668ID'),
        ),
    ]
