# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_time', models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u5904\u7406\u65f6\u95f4')),
                ('handle_user', models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u5904\u7406\u4eba\u5458')),
                ('handle_info', models.TextField(max_length=256, verbose_name='\u4e8b\u9879\u5904\u7406\u4eba\u5458')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_status', models.CharField(choices=[('\u672a\u5f00\u59cb', '\u672a\u5f00\u59cb'), ('\u8fdb\u884c\u4e2d', '\u8fdb\u884c\u4e2d'), ('\u903e\u671f', '\u903e\u671f'), ('\u5df2\u7ed3\u675f', '\u5df2\u7ed3\u675f')], max_length=20, verbose_name='\u4e8b\u9879\u72b6\u6001')),
                ('items_title', models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u6807\u9898')),
                ('items_content', models.CharField(max_length=128, verbose_name='\u4e8b\u9879\u8bf4\u660e')),
                ('items_starter', models.CharField(max_length=64, verbose_name='\u53d1\u8d77\u4eba')),
                ('items_owner', models.CharField(max_length=64, verbose_name='\u4e3b\u529e\u4eba')),
                ('items_relater', models.CharField(max_length=256, verbose_name='\u77e5\u4f1a\u4eba')),
                ('create_time', models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u521b\u5efa\u65f6\u95f4')),
                ('edit_time', models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u4fee\u6539\u65f6\u95f4')),
                ('start_time', models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u7ed3\u675f\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='handledetail',
            name='items_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagement.Items'),
        ),
    ]
