# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handledetail',
            options={'verbose_name': '\u5904\u7406\u8be6\u60c5\u8868', 'verbose_name_plural': '\u5904\u7406\u8be6\u60c5\u8868'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': '\u4e8b\u9879\u603b\u8868', 'verbose_name_plural': '\u4e8b\u9879\u603b\u8868'},
        ),
    ]
