# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0003_auto_20160926_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='edit_time',
            field=models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='items',
            name='end_time',
            field=models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u8ba1\u5212\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='items',
            name='start_time',
            field=models.CharField(max_length=64, verbose_name='\u4e8b\u9879\u8ba1\u5212\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
