# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0004_auto_20160926_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handledetail',
            name='handle_info',
            field=models.TextField(max_length=256, verbose_name='\u4e8b\u9879\u5904\u7406\u610f\u89c1'),
        ),
        migrations.AlterField(
            model_name='handledetail',
            name='items_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagement.Items', verbose_name='\u4e8b\u9879ID'),
        ),
    ]
