# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0008_auto_20160926_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='finish_info',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='\u4e8b\u9879\u7ed3\u675f\u610f\u89c1'),
        ),
    ]
