# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0009_items_finish_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='items_status',
            field=models.CharField(choices=[('\u672a\u5f00\u59cb', '\u672a\u5f00\u59cb'), ('\u8fdb\u884c\u4e2d', '\u8fdb\u884c\u4e2d'), ('\u5df2\u903e\u671f', '\u5df2\u903e\u671f'), ('\u5df2\u7ed3\u675f', '\u5df2\u7ed3\u675f')], max_length=20, verbose_name='\u4e8b\u9879\u72b6\u6001'),
        ),
    ]
