# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='\u7528\u6237ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u59d3\u540d')),
                ('act_moudle', models.CharField(max_length=64, verbose_name='\u64cd\u4f5c\u6a21\u5757')),
                ('act_type', models.CharField(max_length=32, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('act_time', models.CharField(max_length=32, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('act_detail', models.CharField(max_length=128, verbose_name='\u8be6\u60c5')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u7cfb\u7edf\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='SSHLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(default='none', verbose_name='\u5ba2\u6237\u7aefIP')),
                ('cmd_server_group_id', models.TextField(default='none', max_length=512, verbose_name='\u64cd\u4f5c\u670d\u52a1\u5668\u7ec4ID')),
                ('cmd_server_server_id', models.TextField(default='none', max_length=512, verbose_name='\u64cd\u4f5c\u670d\u52a1\u5668ID')),
                ('cmd_time', models.CharField(max_length=64, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('cmd_user', models.CharField(max_length=64, verbose_name='\u64cd\u4f5c\u4eba\u5458')),
                ('cmd_command', models.CharField(max_length=64, verbose_name='\u64cd\u4f5c\u6307\u4ee4')),
            ],
            options={
                'verbose_name': '\u64cd\u4f5c\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u64cd\u4f5c\u65e5\u5fd7\u8868',
            },
        ),
    ]
