# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='act_detail',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='act_moudle',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u6a21\u5757'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='act_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='act_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u64cd\u4f5c\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7528\u6237ID'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7528\u6237\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='sshlog',
            name='cmd_command',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u6307\u4ee4'),
        ),
        migrations.AlterField(
            model_name='sshlog',
            name='cmd_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='sshlog',
            name='cmd_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u4eba\u5458'),
        ),
    ]
