# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_auto_20160919_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='act_moudle',
            new_name='act_module',
        ),
    ]
