# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0003_auto_20160919_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='act_detail',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='\u8be6\u60c5'),
        ),
    ]
