# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0004_auto_20160919_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sshlog',
            options={'verbose_name': '\u8fd0\u7ef4\u64cd\u4f5c\u65e5\u5fd7\u8868', 'verbose_name_plural': '\u8fd0\u7ef4\u64cd\u4f5c\u65e5\u5fd7\u8868'},
        ),
    ]
