# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('device_type', models.CharField(blank=True, default=None, max_length=64, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('device_model', models.CharField(blank=True, default=None, max_length=20, verbose_name='\u8bbe\u5907\u578b\u53f7')),
                ('device_status', models.CharField(blank=True, default=None, max_length=20, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('device_dept', models.CharField(blank=True, default=None, max_length=20, verbose_name='\u4f7f\u7528\u90e8\u95e8')),
                ('device_user', models.CharField(blank=True, default=None, max_length=20, verbose_name='\u4f7f\u7528\u4eba')),
                ('device_memo', models.CharField(blank=True, default=None, max_length=64, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u786c\u4ef6\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u786c\u4ef6\u8d44\u4ea7\u8868',
                'permissions': (('assetinfo_pagedataList', '\u67e5\u770b\u786c\u4ef6\u8d44\u4ea7\u4fe1\u606f\u6743\u9650'), ('assetinfo_editFun', '\u4fee\u6539\u4e0e\u65b0\u589e\u786c\u4ef6\u8d44\u4ea7\u4fe1\u606f\u6743\u9650'), ('assetinfo_deleteFun', '\u5220\u9664\u786c\u4ef6\u8d44\u4ea7\u4fe1\u606f\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=40, unique=True, verbose_name='\u8d44\u6e90ID')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('status', models.CharField(choices=[('\u5728\u7ebf', '\u5728\u7ebf'), ('\u505c\u7528', '\u505c\u7528'), ('\u6d4b\u8bd5', '\u6d4b\u8bd5'), ('\u5907\u7528', '\u5907\u7528'), ('\u5176\u4ed6', '\u5176\u4ed6')], default='\u5728\u7ebf', max_length=20, verbose_name='\u8d44\u4ea7\u72b6\u6001')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='\u5230\u671f\u65e5\u671f')),
                ('admin', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8d44\u4ea7\u7ba1\u7406\u5458')),
                ('tags', models.CharField(blank=True, max_length=64, verbose_name='\u6807\u7b7e')),
                ('memo', models.CharField(blank=True, max_length=256, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u57fa\u7840\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u57fa\u7840\u8d44\u4ea7\u8868',
                'permissions': (('baseinfo_pagedataList', '\u67e5\u770b\u57fa\u7840\u8d44\u4ea7\u6743\u9650'), ('baseinfo_editFun', '\u4fee\u6539\u4e0e\u65b0\u589e\u57fa\u7840\u8d44\u4ea7\u6743\u9650'), ('baseinfo_deleteFun', '\u5220\u9664\u57fa\u7840\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u4e1a\u52a1\u7ebf\u540d\u79f0')),
                ('admin', models.CharField(max_length=64, verbose_name='\u4e1a\u52a1\u7ebf\u6240\u5c5e\u7ba1\u7406\u5458')),
                ('memo', models.CharField(max_length=64, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1\u7ebf',
                'verbose_name_plural': '\u4e1a\u52a1\u7ebf',
                'permissions': (('businessinfo_pagedataList', '\u67e5\u770b\u4e1a\u52a1\u7ebf\u4fe1\u606f\u6743\u9650'), ('businessinfo_editFun', '\u4fee\u6539\u4e0e\u65b0\u589e\u4e1a\u52a1\u7ebf\u4fe1\u606f\u6743\u9650'), ('businessinfo_deleteFun', '\u5220\u9664\u4e1a\u52a1\u7ebf\u4fe1\u606f\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='ConfigInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_info', models.CharField(default=None, max_length=64, verbose_name='CPU\u4fe1\u606f')),
                ('men_info', models.CharField(default=None, max_length=64, verbose_name='\u5185\u5b58\u4fe1\u606f')),
                ('disk_info', models.CharField(default=None, max_length=64, verbose_name='\u786c\u76d8\u4fe1\u606f')),
                ('os', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('public_ip', models.CharField(default='-', max_length=128, verbose_name='\u516c\u7f51IP')),
                ('private_ip', models.CharField(max_length=128, unique=True, verbose_name='\u79c1\u7f51IP')),
                ('mgmt_ip', models.CharField(default=None, max_length=128, verbose_name='\u7ba1\u7406IP')),
                ('memo', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('baseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matrix.BaseInfo', verbose_name='\u8d44\u6e90ID')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u914d\u7f6e\u4fe1\u606f\u8868',
                'permissions': (('configinfo_pagedataList', '\u67e5\u770b\u914d\u7f6e\u4fe1\u606f\u6743\u9650'), ('configinfo_editFun', '\u4fee\u6539\u4e0e\u65b0\u589e\u914d\u7f6e\u4fe1\u606f\u6743\u9650'), ('configinfo_deleteFun', '\u5220\u9664\u914d\u7f6e\u4fe1\u606f\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='DnsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_id', models.CharField(default=None, max_length=64, unique=True, verbose_name='DNS ID\u53f7')),
                ('dns_name', models.CharField(default=None, max_length=64, verbose_name='\u5b50\u57df\u540d\uff08\u4e3b\u673a\u8bb0\u5f55\uff09')),
                ('dns_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8bb0\u5f55\u7c7b\u578b')),
                ('dns_line', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u94fe\u8def\u7c7b\u578b')),
                ('dns_value', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8bb0\u5f55\u503c')),
                ('dns_weight', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u6743\u91cd')),
                ('dns_mx', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='MX\u4f18\u5148\u7ea7')),
                ('dns_ttl', models.IntegerField(blank=True, default=600, null=True)),
                ('dns_enabled', models.CharField(choices=[('1', '\u542f\u7528'), ('0', '\u672a\u542f\u7528')], default='1', max_length=64, verbose_name='\u72b6\u6001')),
                ('dns_remark', models.CharField(blank=True, default=None, max_length=64, verbose_name='\u5907\u6ce8')),
                ('dns_updated_on', models.CharField(blank=True, default=None, max_length=64, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('dnsop', models.CharField(default=None, max_length=64, verbose_name='\u64cd\u4f5c\u4eba\u5458')),
            ],
            options={
                'verbose_name': 'DNS\u4fe1\u606f\u8868',
                'verbose_name_plural': 'DNS\u4fe1\u606f\u8868',
                'permissions': (('dnsinfo_pagedataList', '\u67e5\u770bDNS\u4fe1\u606f\u6743\u9650'), ('dnsinfo_editFun', '\u4fee\u6539\u4e0e\u65b0\u589eDNS\u4fe1\u606f\u6743\u9650'), ('dnsinfo_deleteFun', '\u5220\u9664DNS\u4fe1\u606f\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=20, unique=True, verbose_name='\u57df\u540dID')),
                ('domain_status', models.CharField(max_length=64, verbose_name='\u57df\u540d\u72b6\u6001')),
                ('domain_name', models.CharField(max_length=64, verbose_name='\u57df\u540d')),
                ('domain_records', models.CharField(max_length=256, verbose_name='\u57df\u540d\u8bb0\u5f55\u6761\u6570')),
                ('domain_remark', models.CharField(blank=True, default=None, max_length=64, verbose_name='\u57df\u540d\u5907\u6ce8')),
                ('domain_grade', models.CharField(blank=True, default=None, max_length=64, verbose_name='\u57df\u540d\u5957\u9910\u7b49\u7ea7')),
            ],
            options={
                'verbose_name': '\u57df\u540d\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u57df\u540d\u4fe1\u606f\u8868',
                'permissions': (('domaininfo_pagedataList', '\u67e5\u770bDomain\u4fe1\u606f\u6743\u9650'), ('domaininfo_editFun', '\u4fee\u6539\u4e0e\u65b0\u589eDomain\u4fe1\u606f\u6743\u9650'), ('domaininfo_deleteFun', '\u5220\u9664Domain\u4fe1\u606f\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='DomainRecordLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain_id', models.CharField(max_length=64, verbose_name='\u4e3b\u57df\u540d')),
                ('record_lines_ids', models.CharField(max_length=64, verbose_name='\u7ebf\u8def\u540d\u79f0')),
                ('record_zone', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7ebf\u8def\u8986\u76d6\u533a\u57df')),
                ('record_line_id', models.CharField(max_length=64, verbose_name='\u7ebf\u8defID')),
            ],
            options={
                'verbose_name': '\u57df\u540d\u8bb0\u5f55\u53ef\u9009\u7ebf\u8def\u8868',
                'verbose_name_plural': '\u57df\u540d\u8bb0\u5f55\u53ef\u9009\u7ebf\u8def\u8868',
            },
        ),
        migrations.CreateModel(
            name='DomainRecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(default=None, max_length=32, verbose_name='\u4e3b\u57df\u540d')),
                ('domain_grade', models.CharField(max_length=32, verbose_name='\u57df\u540d\u5957\u9910\u7b49\u7ea7')),
                ('record_type', models.CharField(max_length=256, verbose_name='\u8bb0\u5f55\u53ef\u9009\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u57df\u540d\u8bb0\u5f55\u53ef\u9009\u7c7b\u578b\u8868',
                'verbose_name_plural': '\u57df\u540d\u8bb0\u5f55\u53ef\u9009\u7c7b\u578b\u8868',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u5e73\u53f0\u540d\u79f0')),
                ('domain', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='\u5e73\u53f0\u57df\u540d')),
                ('url', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='URL\u5730\u5740')),
                ('phonecall', models.CharField(max_length=32, verbose_name='\u5e73\u53f0\u7535\u8bdd')),
                ('memo', models.CharField(max_length=64, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u4e91\u5e73\u53f0',
                'verbose_name_plural': '\u4e91\u5e73\u53f0',
                'permissions': (('platforminfo_pagedataList', '\u67e5\u770b\u5e73\u53f0\u4fe1\u606f\u6743\u9650'), ('platforminfo_editFun', '\u4fee\u6539\u4e0e\u65b0\u589e\u5e73\u53f0\u4fe1\u606f\u6743\u9650'), ('platforminfo_deleteFun', '\u5220\u9664\u5e73\u53f0\u4fe1\u606f\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Testmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.CharField(max_length=20, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
            ],
            options={
                'permissions': (('add_test', '\u65b0\u589e\u6570\u636e'), ('change_test', '\u4fee\u6539\u6570\u636e'), ('del_test', '\u5220\u9664\u6570\u636e')),
            },
        ),
        migrations.CreateModel(
            name='ZabbixAlertInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=20, verbose_name='\u4e8b\u4ef6ID')),
                ('alerttime', models.CharField(max_length=64, verbose_name='\u544a\u8b66\u65f6\u95f4')),
                ('subject', models.CharField(max_length=128, verbose_name='\u544a\u8b66\u4e3b\u9898')),
                ('message', models.CharField(max_length=256, verbose_name='\u544a\u8b66\u8be6\u60c5')),
                ('sendto', models.CharField(max_length=64, verbose_name='\u6536\u4ef6\u4eba')),
                ('status', models.CharField(max_length=20, verbose_name='\u544a\u8b66\u72b6\u6001')),
            ],
            options={
                'verbose_name': 'zabbix\u544a\u8b66\u4fe1\u606f\u8868',
                'verbose_name_plural': 'zabbix\u544a\u8b66\u4fe1\u606f\u8868',
                'permissions': (('alarminfo_pagedataList', '\u67e5\u770b\u76d1\u63a7\u65e5\u5fd7'), ('alarminfo_charts', '\u67e5\u770b\u76d1\u63a7\u6298\u7ebf\u56fe'), ('alarminfo_getalert', '\u544a\u8b66\u65e5\u5fd7\u663e\u793a\u544a\u8b66\u5f39\u7a97')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='domainrecordline',
            unique_together=set([('Domain_id', 'record_lines_ids')]),
        ),
        migrations.AddField(
            model_name='dnsinfo',
            name='Domain_name',
            field=models.ForeignKey(default=None, max_length=64, on_delete=django.db.models.deletion.CASCADE, to='Matrix.DomainInfo', verbose_name='\u6240\u5c5e\u57df\u540d'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='business_unit',
            field=models.ManyToManyField(blank=True, null=True, to='Matrix.BusinessUnit', verbose_name='\u6240\u5c5e\u4e1a\u52a1\u7ebf'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='isp',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='Matrix.Platform', verbose_name='\u670d\u52a1\u63d0\u4f9b\u5546'),
        ),
    ]
