# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configinfo',
            name='cpu_info',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='configinfo',
            name='disk_info',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u786c\u76d8\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='configinfo',
            name='men_info',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5185\u5b58\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='configinfo',
            name='mgmt_ip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7ba1\u7406IP'),
        ),
        migrations.AlterField(
            model_name='configinfo',
            name='os',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='configinfo',
            name='public_ip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u516c\u7f51IP'),
        ),
    ]
