# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0002_auto_20160919_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsinfo',
            name='dns_ttl',
            field=models.IntegerField(blank=True, default=600, null=True, verbose_name='ttl'),
        ),
    ]
