# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0003_auto_20160922_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='create_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='expire_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5230\u671f\u65e5\u671f'),
        ),
    ]
