#-*- coding:utf-8 -*-
"""
Django settings for dtop project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os,statvfs

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tcfsko%$_ka***h-7^o2h!s^5xhqco*y#)(=^px8m5ypfg43+p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#SESSION_COOKIE_SECURE = True

#SESSION_COOKIE_HTTPONLY = True

#TEMPLATE_DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Matrix',
    'rest_framework',
    'OM',
    'Log',
    'EventManagement',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dtop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dtop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dtop',
        'USER': 'dtop',
        'PASSWORD': 'Dt9d54e446',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/html/dtop/static/'


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}


apps={'dashboard':{'url':'/home/dashboard.html','name':'开始'},
    'baseinfo':{'url':'/info/baseinfo.html','name':'云资源信息'},
    'hostconfig':{'url':'/info/hostconfig.html','name':'主机配置信息'},
    'businessinfo':{'url':'/info/businessinfo.html','name':'业务线配置信息'},
    'platforminfo':{'url':'/info/platforminfo.html','name':'云平台配置信息'},
    'assetinfo':{'url':'/asset/assetinfo.html','name':'硬件资产信息'},
    'autorelease':{'url':'/auto/autorelease.html','name':'项目发布回滚'},
    'domaininfo':{'url':'/dns/domaininfo.html','name':'域名信息'},
    'dnsinfo':{'url':'/dns/dnsinfo.html','name':'DNS信息'},
    'autodnspod':{'url':'/auto/autodnspod.html','name':'DNS数据同步'},
    'alarminfo':{'url':'/alarm/alarminfo.html','name':'告警日志'},
    'alarmcharts':{'url':'/alarm/alarmcharts.html','name':'告警统计'},
    'usermanagement':{'url':'/auth/usermanagement.html','name':'用户管理'},
    'groupsmanagement':{'url':'/auth/groupsmanagement.html','name':'用户组管理'},
    'wooyunsearch':{'url':'/link/wooyunsearch.html','name':'乌云一下'},
    'om':{'url':'/OM/','name':'运维管理'},
    'em':{'url':'/em/','name':'事项管理'},
    }
vfs=os.statvfs('/')
Size=vfs[statvfs.F_BLOCKS]*vfs[statvfs.F_BSIZE]/(1024*1024*1024)
Avail=vfs[statvfs.F_BAVAIL]*vfs[statvfs.F_BSIZE]/(1024*1024*1024)
Used=Size-Avail
Percent=int(round(round(float(Used)/Size*100,2)))
